[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Molecular Dynamics", "children": [
        {"tag": "protocol_group", "text": "System preparation", "openItem": "False", "children": [
            {"tag": "protocol", "value": "GromacsSystemPrep", "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "MD simulation", "openItem": "False", "children": [
            {"tag": "protocol", "value": "GromacsMDSimulation", "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "Simulation analysis", "openItem": "False", "children": [
            {"tag": "protocol", "value": "GromacsModifySystem", "text": "default"}
        ]}
	]}
	]
