name: Build & test plugin on Pull Request
on:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup enviroment
        uses: scipion-chem/.github/.github/composites/install-scipion@main
      
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
          method: network
          sub-packages: '["nvcc", "toolkit"]'
      
      # Checkout to Pull Request branch if exists
      - name: Clone scipion-chem (in branch ${{ github.head_ref }} if exists, then tries ${{ github.base_ref }}, finally, default branch)
        uses: scipion-chem/.github/.github/composites/clone-in-branch@main
        with:
          path: ${{ github.workspace }}/../
          repo_url: https://github.com/scipion-chem/scipion-chem
          prioritized_branches: "${{ github.head_ref }},${{ github.base_ref }}"
      
      - name: Install scipion-chem
        working-directory: ${{ github.workspace }}/../
        run: scipion/scipion3 installp -p scipion-chem/ --devel
      
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
  
      - name: Install plugin from pull request
        working-directory: ${{ github.workspace }}
        run: |
          pip cache purge
          ../scipion/scipion3 installp -p . --devel
  
      - name: Run tests
        working-directory: ${{ github.workspace }}/${{ vars.FOLDER_WITH_VERSION }}
        run: |
          pip install --user scipion-testrunner
          scipion_testrunner ${{ github.workspace }}/../scipion/scipion3 ${{ vars.FOLDER_WITH_VERSION }} --noGpu --testData=testData.json
